-- Run this script once in the Supabase SQL Editor.
-- It creates a harmless public row used only by the homepage connection test.

create table if not exists public.connection_test (
  id bigint generated by default as identity primary key,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.connection_test enable row level security;

drop policy if exists "Allow public connection test reads"
  on public.connection_test;

create policy "Allow public connection test reads"
  on public.connection_test
  for select
  to anon, authenticated
  using (true);

insert into public.connection_test (id, message)
values (1, 'Connected to Supabase successfully!')
on conflict (id) do update
set message = excluded.message;

grant select on table public.connection_test to anon, authenticated;
