import Link from "next/link";
import { redirect } from "next/navigation";
import { addProgrammeItem, createProgramme, deleteProgramme, publishProgramme, removeProgrammeItem, updateProgrammeItem, updateTemplateItem } from "@/app/app/programmes/actions";
import { PrintProgrammeButton } from "@/components/print-programme-button";
import { FormSubmitButton } from "@/components/form-submit-button";

export const metadata = { title: "Service programmes", description: "Create, publish and review dated service programmes." };
import { WorkspaceNotice } from "@/components/workspace-notice";
import { EmptyState, MetricPill, PageHeader, StatusBadge } from "@/components/workspace-ui";
import { requireProfile } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

const serviceTypes = ["Sunday Service", "Tuesday Service", "Special Service", "Headquarters Service", "Tarry Night"];

type Programme = { id: string; title: string; service_date: string; service_type: string; status: "draft" | "published"; updated_at: string; published_at: string | null };
type ProgrammeItem = { id: string; programme_id: string; position: number; start_time: string; end_time: string; event_name: string; responsible_name: string; duration_minutes: number; notes: string | null };
type Template = { id: string; name: string; active: boolean };
type TemplateItem = { id: string; template_id: string; position: number; start_time: string; end_time: string; event_name: string; responsible_name: string; duration_minutes: number };

function isoDate(date: Date) { return date.toISOString().slice(0, 10); }
function shortTime(value: string) { return value.slice(0, 5); }
function displayDate(value: string) { return new Intl.DateTimeFormat("en-NG", { weekday: "long", day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
function lagosDate() {
  const parts = new Intl.DateTimeFormat("en-GB", { timeZone: "Africa/Lagos", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date());
  const part = (type: Intl.DateTimeFormatPartTypes) => parts.find((item) => item.type === type)?.value ?? "";
  return `${part("year")}-${part("month")}-${part("day")}`;
}

export default async function ProgrammesPage({ searchParams }: { searchParams: Promise<{ programme?: string; template?: string; archive_month?: string; archive_type?: string; message?: string; error?: string }> }) {
  const { profile } = await requireProfile();
  if (!['super_admin', 'church_leader', 'department_head'].includes(profile.role)) redirect('/app');
  const params = await searchParams;
  const supabase = await createClient();
  const [{ data: programmeData, error }, { data: templateData }] = await Promise.all([
    supabase.from("service_programmes").select("id, title, service_date, service_type, status, updated_at, published_at").order("service_date", { ascending: false }).limit(100),
    profile.role === "super_admin" ? supabase.from("service_programme_templates").select("id, name, active").eq("active", true).order("name") : Promise.resolve({ data: [] }),
  ]);
  const programmes = (programmeData ?? []) as Programme[];
  const templates = (templateData ?? []) as Template[];
  const today = lagosDate();
  const upcomingProgrammes = programmes.filter((programme) => programme.service_date >= today).sort((a, b) => a.service_date.localeCompare(b.service_date));
  const pastProgrammes = programmes.filter((programme) => programme.service_date < today).sort((a, b) => b.service_date.localeCompare(a.service_date));
  const archiveMonths = [...new Set(pastProgrammes.map((programme) => programme.service_date.slice(0, 7)))];
  const archivedProgrammes = pastProgrammes.filter((programme) =>
    (!params.archive_month || programme.service_date.startsWith(params.archive_month))
    && (!params.archive_type || programme.service_type === params.archive_type)
  );
  const selected = programmes.find((programme) => programme.id === params.programme) ?? upcomingProgrammes[0] ?? pastProgrammes[0] ?? null;
  const [{ data: itemData }, { data: templateItemData }] = await Promise.all([
    selected ? supabase.from("service_programme_items").select("id, programme_id, position, start_time, end_time, event_name, responsible_name, duration_minutes, notes").eq("programme_id", selected.id).order("position") : Promise.resolve({ data: [] }),
    profile.role === "super_admin" && templates[0] ? supabase.from("service_programme_template_items").select("id, template_id, position, start_time, end_time, event_name, responsible_name, duration_minutes").eq("template_id", templates[0].id).order("position") : Promise.resolve({ data: [] }),
  ]);
  const items = (itemData ?? []) as ProgrammeItem[];
  const templateItems = (templateItemData ?? []) as TemplateItem[];

  return <div className="mx-auto max-w-7xl print:max-w-none">
    <WorkspaceNotice message={params.message} error={params.error ?? error?.message} />
    <div className="print:hidden"><PageHeader eyebrow="Service coordination" title="Service programme" description="Plan, publish and share a dated service schedule with leaders and department heads." actions={selected ? <PrintProgrammeButton /> : undefined} /><div className="mt-6 flex flex-wrap gap-2"><MetricPill value={upcomingProgrammes.length} label="upcoming" /><MetricPill value={pastProgrammes.length} label="archived" /><MetricPill value={programmes.filter((programme) => programme.status === "draft").length} label="drafts" tone={programmes.some((programme) => programme.status === "draft") ? "warning" : "neutral"} /></div></div>

    {profile.role === "super_admin" && <>
      <section className="print:hidden mt-7 rounded-3xl border border-[#dbe3f2] bg-white p-5 shadow-[var(--shadow-sm)] sm:p-6"><h2 className="text-lg font-semibold">Create a dated programme</h2><p className="mt-1 text-sm text-[var(--color-text-muted)]">The selected template is copied, so future template changes will not alter this service.</p><form action={createProgramme} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-[1.3fr_1fr_1fr_1.3fr_auto]"><label className="text-sm font-semibold text-[#68738a]">Template<select name="template_id" required className="mt-2 h-12 w-full rounded-xl border border-[#dce3f1] bg-white px-3 text-sm font-normal">{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label><label className="text-sm font-semibold text-[#68738a]">Service date<input name="service_date" type="date" min={isoDate(new Date())} required className="mt-2 h-12 w-full rounded-xl border border-[#dce3f1] px-3 text-sm font-normal" /></label><label className="text-sm font-semibold text-[#68738a]">Service type<select name="service_type" className="mt-2 h-12 w-full rounded-xl border border-[#dce3f1] bg-white px-3 text-sm font-normal">{serviceTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label className="text-sm font-semibold text-[#68738a]">Programme title<input name="title" defaultValue="Celebrate Jesus Service Schedule" minLength={3} maxLength={160} required className="mt-2 h-12 w-full rounded-xl border border-[#dce3f1] px-3 text-sm font-normal" /></label><FormSubmitButton disabled={!templates.length} pendingLabel="Creating draft..." className="min-h-12 self-end rounded-xl bg-[var(--color-primary)] px-5 text-sm font-semibold text-white hover:bg-[var(--color-primary-strong)] disabled:cursor-wait disabled:bg-[#aebbdc]">Create draft</FormSubmitButton></form></section>

      {templates[0] && <details open={params.template === "open"} className="print:hidden mt-5 rounded-3xl border border-[#e0e6f2] bg-white p-5"><summary className="cursor-pointer font-semibold">Edit reusable Sunday template</summary><p className="mt-2 text-xs text-[#8993a7]">Save each row separately. Changes apply only to programmes created after the change.</p><div className="mt-5 space-y-3">{templateItems.map((item) => <form key={item.id} action={updateTemplateItem} className="grid gap-3 rounded-2xl bg-[#f8faff] p-3 sm:grid-cols-[70px_100px_100px_1fr_1fr_auto] sm:items-end"><input type="hidden" name="id" value={item.id} /><span className="self-center text-xs font-semibold text-[#8993a7]">#{item.position}</span><label className="text-[11px] font-semibold text-[#68738a]">Start<input type="time" name="start_time" defaultValue={shortTime(item.start_time)} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a]">End<input type="time" name="end_time" defaultValue={shortTime(item.end_time)} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a]">Activity<input name="event_name" defaultValue={item.event_name} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a]">Responsible<input name="responsible_name" defaultValue={item.responsible_name} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><FormSubmitButton pendingLabel="Saving..." className="h-10 rounded-lg bg-white px-3 text-xs font-semibold text-[#4168cd] disabled:cursor-wait disabled:opacity-60">Save row</FormSubmitButton></form>)}</div></details>}
    </>}

    <section className="print:hidden mt-7">
      <div><h2 className="text-lg font-semibold">Upcoming programmes</h2><p className="mt-1 text-sm text-[var(--color-text-muted)]">Select any scheduled service to view or manage its programme.</p></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{upcomingProgrammes.map((programme) => <Link key={programme.id} href={`/app/programmes?programme=${programme.id}`} aria-current={selected?.id === programme.id ? "page" : undefined} className={`min-h-28 rounded-2xl border p-4 shadow-[var(--shadow-sm)] transition hover:-translate-y-0.5 hover:shadow-md ${selected?.id === programme.id ? "border-[var(--color-primary)] bg-[var(--color-primary-soft)]" : "border-[var(--color-border)] bg-white"}`}><div className="flex items-center justify-between gap-2"><p className="text-sm font-semibold text-[#34415f]">{programme.service_type}</p><StatusBadge tone={programme.status === "published" ? "success" : "warning"}>{programme.status}</StatusBadge></div><p className="mt-3 text-sm text-[var(--color-text-secondary)]">{displayDate(programme.service_date)}</p><p className="mt-1 truncate text-xs text-[var(--color-text-muted)]">{programme.title}</p></Link>)}</div>
      {!upcomingProgrammes.length && <div className="mt-4"><EmptyState title="No upcoming programme" description={profile.role === "super_admin" ? "Create a dated programme from an active template to begin planning." : "No upcoming programme has been published yet."} /></div>}
    </section>

    {!!pastProgrammes.length && <details open={Boolean(params.archive_month || params.archive_type || (selected && selected.service_date < today))} className="print:hidden mt-5 rounded-3xl border border-[#e0e6f2] bg-white p-5"><summary className="cursor-pointer font-semibold">Programme archive <span className="ml-2 text-xs font-normal text-[#8993a7]">{pastProgrammes.length} past programme{pastProgrammes.length === 1 ? "" : "s"}</span></summary><form method="get" className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><label className="text-xs font-semibold text-[#68738a]">Month<select name="archive_month" defaultValue={params.archive_month ?? ""} className="mt-2 h-11 w-full rounded-xl border border-[#dce3f1] bg-white px-3 text-sm font-normal"><option value="">All months</option>{archiveMonths.map((month) => <option key={month} value={month}>{new Intl.DateTimeFormat("en-NG", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${month}-01T00:00:00Z`))}</option>)}</select></label><label className="text-xs font-semibold text-[#68738a]">Service type<select name="archive_type" defaultValue={params.archive_type ?? ""} className="mt-2 h-11 w-full rounded-xl border border-[#dce3f1] bg-white px-3 text-sm font-normal"><option value="">All service types</option>{serviceTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select></label><button className="self-end rounded-xl bg-[#edf2ff] px-5 py-3 text-sm font-semibold text-[#4168cd]">Filter archive</button></form><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{archivedProgrammes.map((programme) => <Link key={programme.id} href={`/app/programmes?programme=${programme.id}&archive_month=${params.archive_month ?? ""}&archive_type=${params.archive_type ?? ""}`} className={`rounded-2xl border p-4 ${selected?.id === programme.id ? "border-[#4f7df3] bg-[#edf2ff]" : "border-[#e0e6f2] bg-[#f9faff]"}`}><p className="text-sm font-semibold text-[#34415f]">{programme.service_type}</p><p className="mt-2 text-xs text-[#758097]">{displayDate(programme.service_date)}</p><p className="mt-2 truncate text-xs text-[#8993a7]">{programme.title}</p></Link>)}</div>{!archivedProgrammes.length && <p className="mt-5 rounded-2xl bg-[#f8faff] p-5 text-sm text-[#8993a7]">No archived programmes match these filters.</p>}</details>}

    {selected ? <section className="mt-6 overflow-hidden rounded-3xl border border-[#dfe4ee] bg-white print:mt-0 print:border-0">
      <div className="border-b border-[#e5e9f1] px-5 py-6 text-center sm:px-8"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#4f7df3]">TREM Ejigbo</p><h2 className="mt-3 text-2xl font-semibold">{selected.title}</h2><p className="mt-2 font-medium text-[#5f6b82]">{displayDate(selected.service_date)}</p><p className="mt-1 text-xs text-[#8993a7]">{selected.service_type} · Updated {new Intl.DateTimeFormat("en-NG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(selected.updated_at))}</p></div>
      <div className="hidden grid-cols-[120px_1.2fr_1fr_90px] gap-4 border-b border-[#e5e9f1] bg-[#f7f9fd] px-6 py-3 text-xs font-semibold uppercase tracking-[0.08em] text-[#68738a] md:grid"><span>Time</span><span>Activity</span><span>Responsible</span><span>Duration</span></div>
      <div className="divide-y divide-[#edf0f6]">{items.map((item) => profile.role === "super_admin" ? <div key={item.id} className="print:block px-5 py-4"><form action={updateProgrammeItem} className="grid gap-3 md:grid-cols-[60px_100px_100px_1.2fr_1fr_80px_auto] md:items-end"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="programme_id" value={selected.id} /><span className="hidden self-center text-xs font-semibold text-[#8993a7] md:block">#{item.position}</span><label className="text-[11px] font-semibold text-[#68738a] print:hidden">Start<input name="start_time" type="time" defaultValue={shortTime(item.start_time)} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a] print:hidden">End<input name="end_time" type="time" defaultValue={shortTime(item.end_time)} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a] print:hidden">Activity<input name="event_name" defaultValue={item.event_name} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a] print:hidden">Responsible<input name="responsible_name" defaultValue={item.responsible_name} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><span className="hidden self-center text-xs text-[#68738a] md:block print:hidden">{item.duration_minutes} min</span><button className="h-10 rounded-lg bg-[#edf2ff] px-3 text-xs font-semibold text-[#4168cd] print:hidden">Save</button></form><form action={removeProgrammeItem} className="mt-2 text-right print:hidden"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="programme_id" value={selected.id} /><button className="text-[11px] font-semibold text-[#b5524b]">Remove item</button></form><div className="hidden print:grid print:grid-cols-[120px_1.2fr_1fr_90px] print:gap-4 print:text-sm"><span>{shortTime(item.start_time)}–{shortTime(item.end_time)}</span><span>{item.event_name}</span><span>{item.responsible_name}</span><span>{item.duration_minutes} min</span></div></div> : <article key={item.id} className="grid gap-2 px-5 py-4 md:grid-cols-[120px_1.2fr_1fr_90px] md:gap-4 md:px-6"><p className="text-sm font-semibold text-[#4f7df3]">{shortTime(item.start_time)}–{shortTime(item.end_time)}</p><div><p className="text-sm font-semibold text-[#34415f]">{item.event_name}</p>{item.notes && <p className="mt-1 text-xs text-[#8993a7]">{item.notes}</p>}</div><p className="text-sm text-[#5f6b82]">{item.responsible_name}</p><p className="text-xs font-semibold text-[#8993a7] md:text-sm">{item.duration_minutes} min</p></article>)}</div>
      {profile.role === "super_admin" && <details className="print:hidden border-t border-[#e5e9f1] px-5 py-4"><summary className="cursor-pointer text-sm font-semibold text-[#536078]">Add another programme item</summary><form action={addProgrammeItem} className="mt-4 grid gap-3 sm:grid-cols-[110px_110px_1fr_1fr_auto] sm:items-end"><input type="hidden" name="programme_id" value={selected.id} /><label className="text-xs font-semibold text-[#68738a]">Start<input name="start_time" type="time" required className="mt-1 h-11 w-full rounded-lg border border-[#dce3f1] px-2 text-sm" /></label><label className="text-xs font-semibold text-[#68738a]">End<input name="end_time" type="time" required className="mt-1 h-11 w-full rounded-lg border border-[#dce3f1] px-2 text-sm" /></label><label className="text-xs font-semibold text-[#68738a]">Activity<input name="event_name" required className="mt-1 h-11 w-full rounded-lg border border-[#dce3f1] px-3 text-sm" /></label><label className="text-xs font-semibold text-[#68738a]">Responsible<input name="responsible_name" required className="mt-1 h-11 w-full rounded-lg border border-[#dce3f1] px-3 text-sm" /></label><FormSubmitButton pendingLabel="Adding..." className="min-h-11 rounded-lg bg-[var(--color-primary-soft)] px-4 text-sm font-semibold text-[var(--color-primary-strong)] disabled:cursor-wait disabled:opacity-60">Add item</FormSubmitButton></form></details>}
      {profile.role === "super_admin" && <div className="print:hidden sticky bottom-0 z-10 flex flex-col gap-4 border-t border-[#d8e1f3] bg-white/95 px-5 py-4 shadow-[0_-12px_30px_rgba(16,28,61,0.08)] backdrop-blur sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-[var(--color-text)]">{selected.status === "published" ? "Publish your latest changes" : "Ready to share this programme?"}</p><p className="mt-1 text-xs text-[var(--color-text-secondary)]">Review all times first. Publishing makes this schedule visible to leaders and department heads.</p></div><form action={publishProgramme}><input type="hidden" name="programme_id" value={selected.id} /><FormSubmitButton pendingLabel="Publishing..." className="min-h-12 w-full rounded-xl bg-[var(--color-primary)] px-5 text-sm font-semibold text-white hover:bg-[var(--color-primary-strong)] disabled:cursor-wait disabled:opacity-60 sm:w-auto">{selected.status === "published" ? "Republish updates" : "Publish programme"}</FormSubmitButton></form></div>}
      {profile.role === "super_admin" && <details className="print:hidden border-t border-[#f0d7d4] bg-[#fff9f8] px-5 py-4"><summary className="cursor-pointer text-sm font-semibold text-[#a94740]">Delete this programme</summary><div className="mt-3 rounded-xl border border-[#efd4d1] bg-white p-4"><p className="text-xs leading-5 text-[#7d5a57]">This permanently deletes the programme and all its schedule items. It will immediately disappear for church leaders and department heads. This cannot be undone.</p><form action={deleteProgramme} className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto] sm:items-end"><input type="hidden" name="programme_id" value={selected.id} /><label className="text-xs font-semibold text-[#7d5a57]">Enter the exact title to confirm<input name="confirmation" required autoComplete="off" placeholder={selected.title} className="mt-2 h-11 w-full rounded-xl border border-[#dfbbb7] bg-white px-3 text-sm font-normal text-[#34415f]" /></label><FormSubmitButton pendingLabel="Deleting..." className="h-11 rounded-xl bg-[#b5524b] px-5 text-sm font-semibold text-white disabled:cursor-wait disabled:opacity-60">Permanently delete</FormSubmitButton></form></div></details>}
    </section> : <div className="mt-8"><EmptyState title="No service programme available" description={profile.role === "super_admin" ? "Create your first dated programme from the reusable Sunday template." : "A published service programme will appear here when it is ready."} /></div>}
  </div>;
}
