import Link from "next/link";
import { redirect } from "next/navigation";
import { addProgrammeItem, createProgramme, publishProgramme, removeProgrammeItem, updateProgrammeItem, updateTemplateItem } from "@/app/app/programmes/actions";
import { PrintProgrammeButton } from "@/components/print-programme-button";
import { FormSubmitButton } from "@/components/form-submit-button";
import { WorkspaceNotice } from "@/components/workspace-notice";
import { requireProfile } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

const serviceTypes = ["Sunday Service", "Tuesday Service", "Special Service", "Headquarters Service", "Tarry Night"];

type Programme = { id: string; title: string; service_date: string; service_type: string; status: "draft" | "published"; updated_at: string; published_at: string | null };
type ProgrammeItem = { id: string; programme_id: string; position: number; start_time: string; end_time: string; event_name: string; responsible_name: string; duration_minutes: number; notes: string | null };
type Template = { id: string; name: string; active: boolean };
type TemplateItem = { id: string; template_id: string; position: number; start_time: string; end_time: string; event_name: string; responsible_name: string; duration_minutes: number };

function isoDate(date: Date) { return date.toISOString().slice(0, 10); }
function shortTime(value: string) { return value.slice(0, 5); }
function displayDate(value: string) { return new Intl.DateTimeFormat("en-NG", { weekday: "long", day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }

export default async function ProgrammesPage({ searchParams }: { searchParams: Promise<{ programme?: string; template?: string; message?: string; error?: string }> }) {
  const { profile } = await requireProfile();
  if (!['super_admin', 'church_leader', 'department_head'].includes(profile.role)) redirect('/app');
  const params = await searchParams;
  const supabase = await createClient();
  const [{ data: programmeData, error }, { data: templateData }] = await Promise.all([
    supabase.from("service_programmes").select("id, title, service_date, service_type, status, updated_at, published_at").order("service_date", { ascending: false }).limit(100),
    profile.role === "super_admin" ? supabase.from("service_programme_templates").select("id, name, active").eq("active", true).order("name") : Promise.resolve({ data: [] }),
  ]);
  const programmes = (programmeData ?? []) as Programme[];
  const templates = (templateData ?? []) as Template[];
  const selected = programmes.find((programme) => programme.id === params.programme) ?? programmes[0] ?? null;
  const [{ data: itemData }, { data: templateItemData }] = await Promise.all([
    selected ? supabase.from("service_programme_items").select("id, programme_id, position, start_time, end_time, event_name, responsible_name, duration_minutes, notes").eq("programme_id", selected.id).order("position") : Promise.resolve({ data: [] }),
    profile.role === "super_admin" && templates[0] ? supabase.from("service_programme_template_items").select("id, template_id, position, start_time, end_time, event_name, responsible_name, duration_minutes").eq("template_id", templates[0].id).order("position") : Promise.resolve({ data: [] }),
  ]);
  const items = (itemData ?? []) as ProgrammeItem[];
  const templateItems = (templateItemData ?? []) as TemplateItem[];

  return <div className="mx-auto max-w-7xl print:max-w-none">
    <WorkspaceNotice message={params.message} error={params.error ?? error?.message} />
    <div className="print:hidden flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.15em] text-[#4f7df3]">Service coordination</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Service Programme</h1><p className="mt-2 text-sm text-[#758097]">A dated, mobile-friendly schedule shared with leaders and department heads.</p></div>{selected && <PrintProgrammeButton />}</div>

    {profile.role === "super_admin" && <>
      <section className="print:hidden mt-7 rounded-3xl border border-[#dbe3f2] bg-white p-5 sm:p-6"><h2 className="text-lg font-semibold">Create a dated programme</h2><p className="mt-1 text-xs text-[#8993a7]">The selected template is copied, so future template changes will not alter this service.</p><form action={createProgramme} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-[1.3fr_1fr_1fr_1.3fr_auto]"><label className="text-xs font-semibold text-[#68738a]">Template<select name="template_id" required className="mt-2 h-11 w-full rounded-xl border border-[#dce3f1] bg-white px-3 text-sm font-normal">{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label><label className="text-xs font-semibold text-[#68738a]">Service date<input name="service_date" type="date" min={isoDate(new Date())} required className="mt-2 h-11 w-full rounded-xl border border-[#dce3f1] px-3 text-sm font-normal" /></label><label className="text-xs font-semibold text-[#68738a]">Service type<select name="service_type" className="mt-2 h-11 w-full rounded-xl border border-[#dce3f1] bg-white px-3 text-sm font-normal">{serviceTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label className="text-xs font-semibold text-[#68738a]">Programme title<input name="title" defaultValue="Celebrate Jesus Service Schedule" minLength={3} maxLength={160} required className="mt-2 h-11 w-full rounded-xl border border-[#dce3f1] px-3 text-sm font-normal" /></label><button disabled={!templates.length} className="self-end rounded-xl bg-[#4f7df3] px-5 py-3 text-sm font-semibold text-white disabled:bg-[#aebbdc]">Create draft</button></form></section>

      {templates[0] && <details open={params.template === "open"} className="print:hidden mt-5 rounded-3xl border border-[#e0e6f2] bg-white p-5"><summary className="cursor-pointer font-semibold">Edit reusable Sunday template</summary><p className="mt-2 text-xs text-[#8993a7]">Save each row separately. Changes apply only to programmes created after the change.</p><div className="mt-5 space-y-3">{templateItems.map((item) => <form key={item.id} action={updateTemplateItem} className="grid gap-3 rounded-2xl bg-[#f8faff] p-3 sm:grid-cols-[70px_100px_100px_1fr_1fr_auto] sm:items-end"><input type="hidden" name="id" value={item.id} /><span className="self-center text-xs font-semibold text-[#8993a7]">#{item.position}</span><label className="text-[11px] font-semibold text-[#68738a]">Start<input type="time" name="start_time" defaultValue={shortTime(item.start_time)} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a]">End<input type="time" name="end_time" defaultValue={shortTime(item.end_time)} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a]">Activity<input name="event_name" defaultValue={item.event_name} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a]">Responsible<input name="responsible_name" defaultValue={item.responsible_name} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><FormSubmitButton pendingLabel="Saving..." className="h-10 rounded-lg bg-white px-3 text-xs font-semibold text-[#4168cd] disabled:cursor-wait disabled:opacity-60">Save row</FormSubmitButton></form>)}</div></details>}
    </>}

    <div className="print:hidden mt-7 flex gap-3 overflow-x-auto pb-2">{programmes.map((programme) => <Link key={programme.id} href={`/app/programmes?programme=${programme.id}`} className={`min-w-64 rounded-2xl border p-4 ${selected?.id === programme.id ? "border-[#4f7df3] bg-[#edf2ff]" : "border-[#e0e6f2] bg-white"}`}><div className="flex items-center justify-between gap-2"><p className="text-sm font-semibold text-[#34415f]">{programme.service_type}</p><span className={`rounded-full px-2 py-1 text-[10px] font-semibold uppercase ${programme.status === "published" ? "bg-[#e9f7ee] text-[#2f7b50]" : "bg-[#fff4df] text-[#8d641d]"}`}>{programme.status}</span></div><p className="mt-2 text-xs text-[#758097]">{displayDate(programme.service_date)}</p></Link>)}</div>

    {selected ? <section className="mt-6 overflow-hidden rounded-3xl border border-[#dfe4ee] bg-white print:mt-0 print:border-0">
      <div className="border-b border-[#e5e9f1] px-5 py-6 text-center sm:px-8"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#4f7df3]">TREM Ejigbo</p><h2 className="mt-3 text-2xl font-semibold">{selected.title}</h2><p className="mt-2 font-medium text-[#5f6b82]">{displayDate(selected.service_date)}</p><p className="mt-1 text-xs text-[#8993a7]">{selected.service_type} · Updated {new Intl.DateTimeFormat("en-NG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(selected.updated_at))}</p></div>
      <div className="hidden grid-cols-[120px_1.2fr_1fr_90px] gap-4 border-b border-[#e5e9f1] bg-[#f7f9fd] px-6 py-3 text-xs font-semibold uppercase tracking-[0.08em] text-[#68738a] md:grid"><span>Time</span><span>Activity</span><span>Responsible</span><span>Duration</span></div>
      <div className="divide-y divide-[#edf0f6]">{items.map((item) => profile.role === "super_admin" ? <div key={item.id} className="print:block px-5 py-4"><form action={updateProgrammeItem} className="grid gap-3 md:grid-cols-[60px_100px_100px_1.2fr_1fr_80px_auto] md:items-end"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="programme_id" value={selected.id} /><span className="hidden self-center text-xs font-semibold text-[#8993a7] md:block">#{item.position}</span><label className="text-[11px] font-semibold text-[#68738a] print:hidden">Start<input name="start_time" type="time" defaultValue={shortTime(item.start_time)} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a] print:hidden">End<input name="end_time" type="time" defaultValue={shortTime(item.end_time)} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a] print:hidden">Activity<input name="event_name" defaultValue={item.event_name} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a] print:hidden">Responsible<input name="responsible_name" defaultValue={item.responsible_name} required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><span className="hidden self-center text-xs text-[#68738a] md:block print:hidden">{item.duration_minutes} min</span><button className="h-10 rounded-lg bg-[#edf2ff] px-3 text-xs font-semibold text-[#4168cd] print:hidden">Save</button></form><form action={removeProgrammeItem} className="mt-2 text-right print:hidden"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="programme_id" value={selected.id} /><button className="text-[11px] font-semibold text-[#b5524b]">Remove item</button></form><div className="hidden print:grid print:grid-cols-[120px_1.2fr_1fr_90px] print:gap-4 print:text-sm"><span>{shortTime(item.start_time)}–{shortTime(item.end_time)}</span><span>{item.event_name}</span><span>{item.responsible_name}</span><span>{item.duration_minutes} min</span></div></div> : <article key={item.id} className="grid gap-2 px-5 py-4 md:grid-cols-[120px_1.2fr_1fr_90px] md:gap-4 md:px-6"><p className="text-sm font-semibold text-[#4f7df3]">{shortTime(item.start_time)}–{shortTime(item.end_time)}</p><div><p className="text-sm font-semibold text-[#34415f]">{item.event_name}</p>{item.notes && <p className="mt-1 text-xs text-[#8993a7]">{item.notes}</p>}</div><p className="text-sm text-[#5f6b82]">{item.responsible_name}</p><p className="text-xs font-semibold text-[#8993a7] md:text-sm">{item.duration_minutes} min</p></article>)}</div>
      {profile.role === "super_admin" && <details className="print:hidden border-t border-[#e5e9f1] px-5 py-4"><summary className="cursor-pointer text-sm font-semibold text-[#536078]">Add another programme item</summary><form action={addProgrammeItem} className="mt-4 grid gap-3 sm:grid-cols-[100px_100px_1fr_1fr_auto] sm:items-end"><input type="hidden" name="programme_id" value={selected.id} /><label className="text-[11px] font-semibold text-[#68738a]">Start<input name="start_time" type="time" required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a]">End<input name="end_time" type="time" required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a]">Activity<input name="event_name" required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><label className="text-[11px] font-semibold text-[#68738a]">Responsible<input name="responsible_name" required className="mt-1 h-10 w-full rounded-lg border border-[#dce3f1] px-2 text-xs" /></label><button className="h-10 rounded-lg bg-[#edf2ff] px-4 text-xs font-semibold text-[#4168cd]">Add item</button></form></details>}
      {profile.role === "super_admin" && <div className="print:hidden flex items-center justify-between gap-4 border-t border-[#e5e9f1] bg-[#f8faff] px-5 py-4"><p className="text-xs text-[#758097]">Review all times before publishing. Published programmes are immediately visible to leaders and department heads.</p><form action={publishProgramme}><input type="hidden" name="programme_id" value={selected.id} /><button className="rounded-xl bg-[#4f7df3] px-5 py-3 text-sm font-semibold text-white">{selected.status === "published" ? "Republish updates" : "Publish programme"}</button></form></div>}
    </section> : <div className="mt-8 rounded-3xl border border-dashed border-[#d8e0ef] bg-white px-6 py-16 text-center text-sm text-[#8993a7]">{profile.role === "super_admin" ? "Create your first dated programme from the Sunday template." : "No published service programme is available yet."}</div>}
  </div>;
}
