import Link from "next/link";
import { WorkspaceNotice } from "@/components/workspace-notice";

type Department = { id: string; name: string };
type Worker = { id: string; full_name: string; phone_number: string | null; department_id: string; status: string; joined_at: string; whatsapp_opt_in: boolean };

export function WorkerForm({ action, departments, worker, error }: { action: (formData: FormData) => void | Promise<void>; departments: Department[]; worker?: Worker; error?: string }) {
  const input = "mt-2 h-12 w-full rounded-xl border border-[#dce3f1] bg-white px-4 text-sm outline-none focus:border-[#4f7df3]";
  return <div className="mx-auto max-w-3xl"><WorkspaceNotice error={error} /><Link href="/app/workers" className="text-sm font-semibold text-[#4f7df3]">← Back to workers</Link><h1 className="mt-5 text-3xl font-semibold tracking-[-0.035em]">{worker ? "Edit worker" : "Add worker"}</h1><p className="mt-2 text-sm text-[#758097]">Maintain the workforce roster used for attendance and care.</p><form action={action} className="mt-8 grid gap-5 rounded-3xl border border-[#e0e6f2] bg-white p-6 sm:grid-cols-2 sm:p-8">{worker && <input type="hidden" name="id" value={worker.id} />}<label className="text-sm font-medium text-[#34415f] sm:col-span-2">Full name<input className={input} name="full_name" required defaultValue={worker?.full_name} /></label><label className="text-sm font-medium text-[#34415f]">Phone number<input className={input} name="phone_number" type="tel" defaultValue={worker?.phone_number ?? ""} /></label><label className="text-sm font-medium text-[#34415f]">Joined date<input className={input} name="joined_at" type="date" required defaultValue={worker?.joined_at ?? new Date().toISOString().slice(0, 10)} /></label><label className="text-sm font-medium text-[#34415f]">Department<select className={input} name="department_id" required defaultValue={worker?.department_id ?? ""}><option value="" disabled>Select department</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></label><label className="text-sm font-medium text-[#34415f]">Status<select className={input} name="status" defaultValue={worker?.status ?? "Active"}><option>Active</option><option>On Leave</option><option>Inactive</option></select></label><label className="flex items-start gap-3 rounded-2xl bg-[#f6f8fd] p-4 sm:col-span-2"><input type="checkbox" name="whatsapp_opt_in" defaultChecked={worker?.whatsapp_opt_in} className="mt-1 h-4 w-4 accent-[#4f7df3]" /><span><span className="block text-sm font-semibold text-[#34415f]">WhatsApp care messages enabled</span><span className="mt-1 block text-xs leading-5 text-[#7b8599]">Confirm that the worker has agreed to receive automated absence check-ins.</span></span></label><div className="flex justify-end gap-3 sm:col-span-2"><Link href="/app/workers" className="rounded-xl border border-[#dce3f1] px-5 py-3 text-sm font-semibold text-[#5e6a81]">Cancel</Link><button className="rounded-xl bg-[#4f7df3] px-6 py-3 text-sm font-semibold text-white">{worker ? "Save changes" : "Add worker"}</button></div></form></div>;
}
